// <auto-generated />
using System;
using GYM.Infraestructura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RRHH.Migrations
{
    [DbContext(typeof(GYM_DBContext))]
    [Migration("20260530214433_m0")]
    partial class m0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GYM.Core.Models.Asistencia", b =>
                {
                    b.Property<int>("id_asistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_asistencia"));

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.HasKey("id_asistencia");

                    b.HasIndex("fecha")
                        .IsUnique();

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("GYM.Core.Models.Auditoria", b =>
                {
                    b.Property<int>("id_auditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_auditoria"));

                    b.Property<string>("accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("datos_anteriores")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("datos_nuevos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_registro")
                        .HasColumnType("integer");

                    b.Property<string>("tabla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_auditoria");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("GYM.Core.Models.Categoria", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_categoria"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_categoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GYM.Core.Models.Cliente", b =>
                {
                    b.Property<int>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_cliente"));

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.Property<int>("id_persona")
                        .HasColumnType("integer");

                    b.Property<string>("pwd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_cliente");

                    b.HasIndex("id_persona");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GYM.Core.Models.Correo", b =>
                {
                    b.Property<int>("id_correo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_correo"));

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.HasKey("id_correo");

                    b.HasIndex("correo")
                        .IsUnique();

                    b.ToTable("Correos");
                });

            modelBuilder.Entity("GYM.Core.Models.DetalleVenta", b =>
                {
                    b.Property<int>("id_venta")
                        .HasColumnType("integer");

                    b.Property<int>("id_producto")
                        .HasColumnType("integer");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.HasKey("id_venta", "id_producto");

                    b.HasIndex("id_producto");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("GYM.Core.Models.EmpleadoTurno", b =>
                {
                    b.Property<int>("id_empleado")
                        .HasColumnType("integer");

                    b.Property<int>("id_turno")
                        .HasColumnType("integer");

                    b.HasKey("id_empleado", "id_turno");

                    b.HasIndex("id_turno");

                    b.ToTable("EmpleadoTurnos");
                });

            modelBuilder.Entity("GYM.Core.Models.Inventario", b =>
                {
                    b.Property<int>("id_inventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_inventario"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_inventario");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("GYM.Core.Models.Membresia", b =>
                {
                    b.Property<int>("id_membresia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_membresia"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("duracion")
                        .HasColumnType("integer");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("precio")
                        .HasColumnType("numeric");

                    b.HasKey("id_membresia");

                    b.ToTable("Membresias");
                });

            modelBuilder.Entity("GYM.Core.Models.Persona", b =>
                {
                    b.Property<int>("id_persona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_persona"));

                    b.Property<string>("apellido_m")
                        .HasColumnType("text");

                    b.Property<string>("apellido_p")
                        .HasColumnType("text");

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("fecha_nacimiento")
                        .HasColumnType("date");

                    b.Property<string>("hashhuella")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("sexo")
                        .HasColumnType("boolean");

                    b.HasKey("id_persona");

                    b.HasIndex("ci")
                        .IsUnique();

                    b.HasIndex("hashhuella")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("GYM.Core.Models.PersonaAsistencia", b =>
                {
                    b.Property<int>("id_persona")
                        .HasColumnType("integer");

                    b.Property<int>("id_asistencia")
                        .HasColumnType("integer");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.HasKey("id_persona", "id_asistencia");

                    b.HasIndex("id_asistencia");

                    b.HasIndex("id_persona", "id_asistencia")
                        .IsUnique();

                    b.ToTable("PersonaAsistencias");
                });

            modelBuilder.Entity("GYM.Core.Models.PersonaCorreo", b =>
                {
                    b.Property<int>("id_persona")
                        .HasColumnType("integer");

                    b.Property<int>("id_correo")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fecha_inicio")
                        .HasColumnType("date");

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("fecha_fin")
                        .HasColumnType("date");

                    b.HasKey("id_persona", "id_correo", "fecha_inicio");

                    b.HasIndex("id_correo");

                    b.HasIndex("ci", "correo", "fecha_inicio")
                        .IsUnique();

                    b.ToTable("PersonaCorreos");
                });

            modelBuilder.Entity("GYM.Core.Models.PersonaTelefono", b =>
                {
                    b.Property<int>("id_persona")
                        .HasColumnType("integer");

                    b.Property<int>("id_telefono")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fecha_inicio")
                        .HasColumnType("date");

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("fecha_fin")
                        .HasColumnType("date");

                    b.Property<string>("telf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_persona", "id_telefono", "fecha_inicio");

                    b.HasIndex("id_telefono");

                    b.HasIndex("ci", "telf", "fecha_inicio")
                        .IsUnique();

                    b.ToTable("PersonaTelefonos");
                });

            modelBuilder.Entity("GYM.Core.Models.Producto", b =>
                {
                    b.Property<int>("id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_producto"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_categoria")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("precio")
                        .HasColumnType("numeric");

                    b.HasKey("id_producto");

                    b.HasIndex("id_categoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("GYM.Core.Models.Stock", b =>
                {
                    b.Property<int>("id_inventario")
                        .HasColumnType("integer");

                    b.Property<int>("id_producto")
                        .HasColumnType("integer");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.HasKey("id_inventario", "id_producto");

                    b.HasIndex("id_producto");

                    b.ToTable("Stocks", (string)null);
                });

            modelBuilder.Entity("GYM.Core.Models.Suscripcion", b =>
                {
                    b.Property<int>("id_cliente")
                        .HasColumnType("integer");

                    b.Property<int>("id_membresia")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fecha_inicio")
                        .HasColumnType("date");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("fecha_fin")
                        .HasColumnType("date");

                    b.HasKey("id_cliente", "id_membresia", "fecha_inicio");

                    b.HasIndex("id_membresia");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("GYM.Core.Models.Telefono", b =>
                {
                    b.Property<int>("id_telefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_telefono"));

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<string>("telf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_telefono");

                    b.HasIndex("telf")
                        .IsUnique();

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("GYM.Core.Models.Turno", b =>
                {
                    b.Property<int>("id_turno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_turno"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<string>("hora_fin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("hora_inicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_turno");

                    b.HasIndex("codigo")
                        .IsUnique();

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Models.Cargo", b =>
                {
                    b.Property<int>("Cargo_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cargo_Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.HasKey("Cargo_Id");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("Models.CargoSalario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cargo_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha_Fin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fecha_Inicio")
                        .HasColumnType("date");

                    b.Property<int>("Id_Cargo")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Salario")
                        .HasColumnType("integer");

                    b.Property<int>("Salario_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Cargo_Id");

                    b.HasIndex("Salario_Id");

                    b.ToTable("CargoSalario");
                });

            modelBuilder.Entity("Models.Empleado", b =>
                {
                    b.Property<int>("id_empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_empleado"));

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.Property<int>("id_persona")
                        .HasColumnType("integer");

                    b.Property<string>("pwd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_empleado");

                    b.HasIndex("id_persona");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Models.EmpleadoCargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cargo_Id")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaIncio")
                        .HasColumnType("date");

                    b.Property<int>("Id_Cargo")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Empleado")
                        .HasColumnType("integer");

                    b.Property<int>("id_Empleado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Cargo_Id");

                    b.HasIndex("id_Empleado");

                    b.ToTable("EmpleadoCargo");
                });

            modelBuilder.Entity("Models.Salario", b =>
                {
                    b.Property<int>("Salario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Salario_Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Salarioo")
                        .HasColumnType("integer");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.HasKey("Salario_Id");

                    b.ToTable("Salario");
                });

            modelBuilder.Entity("Models.Ventas", b =>
                {
                    b.Property<int>("id_venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_venta"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("date");

                    b.Property<int>("id_cliente")
                        .HasColumnType("integer");

                    b.Property<int>("id_empleado")
                        .HasColumnType("integer");

                    b.HasKey("id_venta");

                    b.HasIndex("id_cliente");

                    b.HasIndex("id_empleado");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("GYM.Core.Models.Cliente", b =>
                {
                    b.HasOne("GYM.Core.Models.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("id_persona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("GYM.Core.Models.DetalleVenta", b =>
                {
                    b.HasOne("GYM.Core.Models.Producto", "producto")
                        .WithMany()
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Ventas", "ventas")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("id_venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("producto");

                    b.Navigation("ventas");
                });

            modelBuilder.Entity("GYM.Core.Models.EmpleadoTurno", b =>
                {
                    b.HasOne("Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("id_empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM.Core.Models.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("id_turno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("GYM.Core.Models.PersonaAsistencia", b =>
                {
                    b.HasOne("GYM.Core.Models.Asistencia", "asistencia")
                        .WithMany("PersonaAsistencias")
                        .HasForeignKey("id_asistencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM.Core.Models.Persona", "persona")
                        .WithMany("PersonaAsistencias")
                        .HasForeignKey("id_persona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asistencia");

                    b.Navigation("persona");
                });

            modelBuilder.Entity("GYM.Core.Models.PersonaCorreo", b =>
                {
                    b.HasOne("GYM.Core.Models.Correo", "Correo")
                        .WithMany("PersonaCorreos")
                        .HasForeignKey("id_correo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM.Core.Models.Persona", "persona")
                        .WithMany("PersonaCorreos")
                        .HasForeignKey("id_persona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Correo");

                    b.Navigation("persona");
                });

            modelBuilder.Entity("GYM.Core.Models.PersonaTelefono", b =>
                {
                    b.HasOne("GYM.Core.Models.Persona", "persona")
                        .WithMany("PersonaTelefonos")
                        .HasForeignKey("id_persona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM.Core.Models.Telefono", "Telefono")
                        .WithMany("PersonaTelefonos")
                        .HasForeignKey("id_telefono")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Telefono");

                    b.Navigation("persona");
                });

            modelBuilder.Entity("GYM.Core.Models.Producto", b =>
                {
                    b.HasOne("GYM.Core.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("id_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GYM.Core.Models.Stock", b =>
                {
                    b.HasOne("GYM.Core.Models.Inventario", "inventario")
                        .WithMany("Stocks")
                        .HasForeignKey("id_inventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM.Core.Models.Producto", "producto")
                        .WithMany("Stocks")
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("inventario");

                    b.Navigation("producto");
                });

            modelBuilder.Entity("GYM.Core.Models.Suscripcion", b =>
                {
                    b.HasOne("GYM.Core.Models.Cliente", "cliente")
                        .WithMany("Suscripciones")
                        .HasForeignKey("id_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM.Core.Models.Membresia", "membresia")
                        .WithMany("Suscripciones")
                        .HasForeignKey("id_membresia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");

                    b.Navigation("membresia");
                });

            modelBuilder.Entity("Models.CargoSalario", b =>
                {
                    b.HasOne("Models.Cargo", "cargo")
                        .WithMany("CargoSalarioo")
                        .HasForeignKey("Cargo_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Salario", "salario")
                        .WithMany("CargoSalario")
                        .HasForeignKey("Salario_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cargo");

                    b.Navigation("salario");
                });

            modelBuilder.Entity("Models.Empleado", b =>
                {
                    b.HasOne("GYM.Core.Models.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("id_persona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("persona");
                });

            modelBuilder.Entity("Models.EmpleadoCargo", b =>
                {
                    b.HasOne("Models.Cargo", "cargo")
                        .WithMany()
                        .HasForeignKey("Cargo_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Empleado", "empleado")
                        .WithMany("empleadocargo")
                        .HasForeignKey("id_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cargo");

                    b.Navigation("empleado");
                });

            modelBuilder.Entity("Models.Ventas", b =>
                {
                    b.HasOne("GYM.Core.Models.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("id_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Empleado", "Empleado")
                        .WithMany("Ventas")
                        .HasForeignKey("id_empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GYM.Core.Models.Asistencia", b =>
                {
                    b.Navigation("PersonaAsistencias");
                });

            modelBuilder.Entity("GYM.Core.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("GYM.Core.Models.Cliente", b =>
                {
                    b.Navigation("Suscripciones");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("GYM.Core.Models.Correo", b =>
                {
                    b.Navigation("PersonaCorreos");
                });

            modelBuilder.Entity("GYM.Core.Models.Inventario", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("GYM.Core.Models.Membresia", b =>
                {
                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("GYM.Core.Models.Persona", b =>
                {
                    b.Navigation("PersonaAsistencias");

                    b.Navigation("PersonaCorreos");

                    b.Navigation("PersonaTelefonos");
                });

            modelBuilder.Entity("GYM.Core.Models.Producto", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("GYM.Core.Models.Telefono", b =>
                {
                    b.Navigation("PersonaTelefonos");
                });

            modelBuilder.Entity("Models.Cargo", b =>
                {
                    b.Navigation("CargoSalarioo");
                });

            modelBuilder.Entity("Models.Empleado", b =>
                {
                    b.Navigation("Ventas");

                    b.Navigation("empleadocargo");
                });

            modelBuilder.Entity("Models.Salario", b =>
                {
                    b.Navigation("CargoSalario");
                });

            modelBuilder.Entity("Models.Ventas", b =>
                {
                    b.Navigation("DetallesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
